Repository 0chain/0chain, pull requests merged in 2021-11, with the labels that each got.

#633 Fix min lock demand
  code/go/0chain.net/smartcontract/storagesc/alloation2_test.go
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/allocation_write_pools.go
Labels: bug

#604 allow owner to transfer ownership
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/allocation_test.go
Labels: enhancement

#619 Add min_write_price for blobbers
  code/go/0chain.net/smartcontract/storagesc/benchmark_setup.go
  code/go/0chain.net/smartcontract/storagesc/config.go
  code/go/0chain.net/smartcontract/storagesc/config_settigns.go
  code/go/0chain.net/smartcontract/storagesc/config_settings_test.go
  code/go/0chain.net/smartcontract/storagesc/helper_test.go
  code/go/0chain.net/smartcontract/storagesc/models.go
  docker.local/config/sc.yaml
Labels: enhancement

#605 Update allocaion request, optinally update blobber terms
  code/go/0chain.net/smartcontract/storagesc/allocation.go
Labels: enhancement

#713 Fix incorrect display of Finalization count stats on '/miner_stats' page
  code/go/0chain.net/chaincore/chain/protocol_block.go
Labels: bug

#695 node crash on mn-update-config
  code/go/0chain.net/smartcontract/minersc/globals.go
  code/go/0chain.net/smartcontract/minersc/handler.go
  code/go/0chain.net/smartcontract/minersc/models.go
  code/go/0chain.net/smartcontract/minersc/sc.go
  code/go/0chain.net/smartcontract/minersc/settings.go
  code/go/0chain.net/smartcontract/minersc/settings_test.go
  code/go/0chain.net/smartcontract/storagesc/config.go
  code/go/0chain.net/smartcontract/storagesc/config_settigns.go
Labels: bug, mainnet

#691 Blobber events table
  code/go/0chain.net/chaincore/chain/entity.go
  code/go/0chain.net/chaincore/chain/state/state_context.go
  code/go/0chain.net/chaincore/chain/state_handler_test.go
  code/go/0chain.net/go.mod
  code/go/0chain.net/go.sum
  code/go/0chain.net/smartcontract/benchmark/benchmark.go
  code/go/0chain.net/smartcontract/benchmark/main/cmd/mpt.go
  code/go/0chain.net/smartcontract/benchmark/main/config/benchmark.yaml
  code/go/0chain.net/smartcontract/benchmark/main/readme.md
  code/go/0chain.net/smartcontract/dbs/db.go
  code/go/0chain.net/smartcontract/dbs/event/blobber.go
  code/go/0chain.net/smartcontract/dbs/event/blobber_test.go
  code/go/0chain.net/smartcontract/dbs/event/event.go
  code/go/0chain.net/smartcontract/dbs/event/event_test.go
  code/go/0chain.net/smartcontract/dbs/event/eventdb.go
  code/go/0chain.net/smartcontract/dbs/event/process.go
  code/go/0chain.net/smartcontract/dbs/postgresql/postresql.go
  code/go/0chain.net/smartcontract/interestpoolsc/balances_test.go
  code/go/0chain.net/smartcontract/interestpoolsc/sc2_test.go
  code/go/0chain.net/smartcontract/minersc/balances_test.go
  code/go/0chain.net/smartcontract/minersc/handler.go
  code/go/0chain.net/smartcontract/minersc/helper2_test.go
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/balances_test.go
  code/go/0chain.net/smartcontract/storagesc/benchmark_setup.go
  code/go/0chain.net/smartcontract/storagesc/blobber.go
  code/go/0chain.net/smartcontract/storagesc/blobber_main.go
  code/go/0chain.net/smartcontract/storagesc/eventdb.go
  code/go/0chain.net/smartcontract/storagesc/free_allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/handler.go
  code/go/0chain.net/smartcontract/storagesc/helper2_test.go
  code/go/0chain.net/smartcontract/vestingsc/balances_test.go
  docker.local/build.sharder/b0docker-compose-debug.yml
  docker.local/build.sharder/b0docker-compose.yml
Labels: enhancement

#689 Integrate 0chain/magic-block repo
  code/go/0chain.net/chaincore/block/magicBlock/main.go
  code/go/0chain.net/chaincore/block/magicBlock/yaml.go
  code/go/0chain.net/chaincore/client/entity.go
  code/go/0chain.net/chaincore/node/node.go
  docker.local/build.unit_test/Dockerfile
Labels: enhancement, mainnet

#712 Do not verify block and use the RRS of the block before VRF shares meet the threshold
  code/go/0chain.net/chaincore/node/n2n_handler.go
  code/go/0chain.net/chaincore/node/n2n_send.go
  code/go/0chain.net/miner/chain.go
  code/go/0chain.net/miner/m_handler.go
  code/go/0chain.net/miner/protocol_bls.go
  code/go/0chain.net/miner/protocol_receive.go
  code/go/0chain.net/miner/protocol_round.go
  code/go/0chain.net/miner/round.go
  code/go/0chain.net/miner/round_test.go
Labels: Wait To Merge, mainnet, byzantine
