Repository 0chain/0chain, pull requests merged in 2021-06, with the labels that each got.

#339 Protect memroystore connection obejct with a mutex
  code/go/0chain.net/core/memorystore/connection.go
  code/go/0chain.net/core/memorystore/connection_test.go
Labels: bug

#377 readPoolLock creates read pool if necessary.
  code/go/0chain.net/smartcontract/storagesc/readpool.go
  code/go/0chain.net/smartcontract/storagesc/readpool_test.go
Labels: bug

#366 Add curator and transfer allocatin ownership
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/models.go
  code/go/0chain.net/smartcontract/storagesc/sc.go
  code/go/0chain.net/smartcontract/storagesc/writepool.go
Labels: enhancement

#361 Fixes for smart contract blobber add/update methods
  code/go/0chain.net/smartcontract/storagesc/blobber.go
  code/go/0chain.net/smartcontract/storagesc/blobber_integration_tests.go
  code/go/0chain.net/smartcontract/storagesc/blobber_main.go
  code/go/0chain.net/smartcontract/storagesc/blobber_test.go
  code/go/0chain.net/smartcontract/storagesc/sc.go
Labels: enhancement, refactor

#358 Free storage allocation
  code/go/0chain.net/go.sum
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/config.go
  code/go/0chain.net/smartcontract/storagesc/free_allocation.go
  code/go/0chain.net/smartcontract/storagesc/free_allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/sc.go
  code/go/0chain.net/smartcontract/storagesc/writepool.go
  code/go/0chain.net/smartcontract/storagesc/writepool_test.go
  config/sc.yaml
  docker.local/config/sc.yaml
Labels: enhancement

#325 Unit test doc
  docs/unit-tests.md
Labels: documentation

#317 Blobber block rewards
  code/go/0chain.net/chaincore/config/dev_config.go
  code/go/0chain.net/miner/protocol_block.go
  code/go/0chain.net/miner/protocol_block_integration_tests.go
  code/go/0chain.net/miner/protocol_block_main.go
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/block_reward.go
  code/go/0chain.net/smartcontract/storagesc/block_reward_test.go
  code/go/0chain.net/smartcontract/storagesc/challenge.go
  code/go/0chain.net/smartcontract/storagesc/challengepool.go
  code/go/0chain.net/smartcontract/storagesc/config.go
  code/go/0chain.net/smartcontract/storagesc/config_test.go
  code/go/0chain.net/smartcontract/storagesc/functions.go
  code/go/0chain.net/smartcontract/storagesc/functions_test.go
  code/go/0chain.net/smartcontract/storagesc/sc.go
  code/go/0chain.net/smartcontract/storagesc/stakepool_test.go
  code/go/0chain.net/smartcontract/storagesc/writepool.go
  config/0chain.yaml
  config/sc.yaml
  docker.local/config/0chain.yaml
  docker.local/config/sc.yaml
Labels: enhancement

#315 Select diverse blobbers by geo location
  code/go/0chain.net/smartcontract/storagesc/alloation2_test.go
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/free_allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/handler.go
  code/go/0chain.net/smartcontract/storagesc/models.go
  code/go/0chain.net/smartcontract/storagesc/models_test.go
Labels: enhancement

#383 writePoolLock creats a new wrteipool if non exists
  code/go/0chain.net/smartcontract/storagesc/writepool.go
  code/go/0chain.net/smartcontract/storagesc/writepool_test.go
Labels: bug
