Repository 0chain/0chain, pull requests merged in 2022-01, with the labels that each got.

#876 Conductor tests build fix
  code/go/0chain.net/chaincore/chain/handler_integration_tests.go
  code/go/0chain.net/miner/protocol_block_integration_tests.go
Labels: byzantine

#883 Events DB: Validator Table
  code/go/0chain.net/chaincore/smartcontract/handler_test.go
  code/go/0chain.net/go.mod
  code/go/0chain.net/smartcontract/dbs/event/event_test.go
  code/go/0chain.net/smartcontract/dbs/event/eventdb.go
  code/go/0chain.net/smartcontract/dbs/event/process.go
  code/go/0chain.net/smartcontract/dbs/event/validator.go
  code/go/0chain.net/smartcontract/dbs/event/validator_test.go
  code/go/0chain.net/smartcontract/storagesc/benchmark_rest_tests.go
  code/go/0chain.net/smartcontract/storagesc/handler.go
  code/go/0chain.net/smartcontract/storagesc/sc.go
  code/go/0chain.net/smartcontract/storagesc/stakepool.go
  code/go/0chain.net/smartcontract/storagesc/validator.go
  code/go/0chain.net/smartcontract/storagesc/validator_eventdb.go
Labels: Event database

#888 Hotfix to remove DbAccess settings from MPT
  code/go/0chain.net/chaincore/chain/config.go
  code/go/0chain.net/smartcontract/minersc/globals.go
  code/go/0chain.net/smartcontract/minersc/globals_test.go
Labels: high-priority

#930 Feature/transaction errors
  code/go/0chain.net/chaincore/block/entity.go
  code/go/0chain.net/chaincore/chain/block_fetcher.go
  code/go/0chain.net/chaincore/chain/config.go
  code/go/0chain.net/chaincore/chain/entity.go
  code/go/0chain.net/chaincore/chain/protocol_block.go
  code/go/0chain.net/chaincore/chain/protocol_round.go
  code/go/0chain.net/chaincore/chain/state.go
  code/go/0chain.net/chaincore/chain/state_sync.go
  code/go/0chain.net/chaincore/httpclientutil/http_client_util.go
  code/go/0chain.net/chaincore/httpclientutil/http_client_util_test.go
  code/go/0chain.net/chaincore/node/n2n_request.go
  code/go/0chain.net/chaincore/node/n2n_send.go
  code/go/0chain.net/chaincore/node/worker.go
  code/go/0chain.net/chaincore/round/entity.go
  code/go/0chain.net/chaincore/transaction/status.go
  code/go/0chain.net/chaincore/transaction/type.go
  code/go/0chain.net/core/encryption/handler.go
  code/go/0chain.net/miner/chain.go
  code/go/0chain.net/miner/m_handler.go
  code/go/0chain.net/miner/miner_test.go
  code/go/0chain.net/miner/protocol_block.go
  code/go/0chain.net/miner/protocol_block_main.go
  code/go/0chain.net/miner/protocol_receive.go
  code/go/0chain.net/miner/protocol_round.go
  code/go/0chain.net/miner/round.go
  code/go/0chain.net/smartcontract/minersc/models.go
  code/go/0chain.net/smartcontract/storagesc/blobber_test.go
  docker.local/config/0chain.yaml
  docker.local/config/b0magicBlock_3_miners_3_sharders.json
  docker.local/config/b0mnode1_3_miners_3_sharders_dkg.json
  docker.local/config/b0mnode2_3_miners_3_sharders_dkg.json
  docker.local/config/b0mnode3_3_miners_3_sharders_dkg.json
Labels: enhancement, mainnet
