Repository 0chain/0chain, pull requests merged in 2022-07, with the labels that each got.

#1513 Free Allocation bugfix
  code/go/0chain.net/smartcontract/dbs/event/blobber.go
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/handler.go
  code/go/0chain.net/smartcontract/storagesc/helper_test.go
  code/go/0chain.net/smartcontract/storagesc/models.go
  code/go/0chain.net/smartcontract/storagesc/stakepool.go
Labels: bug, mainnet

#1512 Blobber update validation
  code/go/0chain.net/chaincore/chain/protocol_block.go
  code/go/0chain.net/chaincore/currency/currency.go
  code/go/0chain.net/smartcontract/minersc/fees.go
  code/go/0chain.net/smartcontract/stakepool/stakepool.go
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/blobber.go
  code/go/0chain.net/smartcontract/storagesc/block_reward.go
  code/go/0chain.net/smartcontract/storagesc/challengepool.go
  code/go/0chain.net/smartcontract/storagesc/models.go
  code/go/0chain.net/smartcontract/storagesc/stakepool.go
  docker.local/config/sc.yaml
Labels: mainnet

#1525 fied type
  code/go/0chain.net/smartcontract/storagesc/handler.go
Labels: bug, mainnet

#1521 new free allocation mint logic
  code/go/0chain.net/smartcontract/benchmark/benchmark.go
  code/go/0chain.net/smartcontract/benchmark/main/config/benchmark.yaml
  code/go/0chain.net/smartcontract/stakepool/lock.go
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/benchmark_setup.go
  code/go/0chain.net/smartcontract/storagesc/benchmark_tests.go
  code/go/0chain.net/smartcontract/storagesc/blobber_test.go
  code/go/0chain.net/smartcontract/storagesc/config.go
  code/go/0chain.net/smartcontract/storagesc/config_gen.go
  code/go/0chain.net/smartcontract/storagesc/config_settigns.go
  code/go/0chain.net/smartcontract/storagesc/config_settings_test.go
  code/go/0chain.net/smartcontract/storagesc/free_allocation.go
  code/go/0chain.net/smartcontract/storagesc/free_allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/models.go
  code/go/0chain.net/smartcontract/storagesc/readpool.go
  code/go/0chain.net/smartcontract/storagesc/readpool_gen.go
  code/go/0chain.net/smartcontract/storagesc/writepool.go
  docker.local/config/sc.yaml
Labels: bug, mainnet

#1541 fixed client event wrong ordering
  code/go/0chain.net/chaincore/chain/state.go
  code/go/0chain.net/chaincore/chain/state/state_context.go
  code/go/0chain.net/smartcontract/minersc/balances_test.go
  code/go/0chain.net/smartcontract/minersc/helper2_test.go
  code/go/0chain.net/smartcontract/stakepool/balances_test.go
  code/go/0chain.net/smartcontract/storagesc/balances_test.go
  code/go/0chain.net/smartcontract/storagesc/handler.go
  code/go/0chain.net/smartcontract/storagesc/helper2_test.go
  code/go/0chain.net/smartcontract/vestingsc/balances_test.go
Labels: bug, mainnet, high-priority, Event database
