Repository 0chain/0chain, pull requests merged in 2022-05, with the labels that each got.

#1211 Implement TTL for open challenges
  code/go/0chain.net/chaincore/chain/config.go
  code/go/0chain.net/chaincore/chain/entity.go
  code/go/0chain.net/chaincore/chain/state.go
  code/go/0chain.net/chaincore/chain/state/state_context.go
  code/go/0chain.net/chaincore/chain/state_handler_test.go
  code/go/0chain.net/chaincore/config/config.go
  code/go/0chain.net/core/common/time.go
  code/go/0chain.net/miner/miner/main.go
  code/go/0chain.net/smartcontract/benchmark/main/cmd/mpt.go
  code/go/0chain.net/smartcontract/interestpoolsc/balances_test.go
  code/go/0chain.net/smartcontract/interestpoolsc/sc2_test.go
  code/go/0chain.net/smartcontract/minersc/balances_test.go
  code/go/0chain.net/smartcontract/minersc/fees2_test.go
  code/go/0chain.net/smartcontract/minersc/helper2_test.go
  code/go/0chain.net/smartcontract/partitions/partitions.go
  code/go/0chain.net/smartcontract/storagesc/alloation2_test.go
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/allocation_eventdb.go
  code/go/0chain.net/smartcontract/storagesc/allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/balances_test.go
  code/go/0chain.net/smartcontract/storagesc/benchmark_setup.go
  code/go/0chain.net/smartcontract/storagesc/benchmark_tests.go
  code/go/0chain.net/smartcontract/storagesc/blobber.go
  code/go/0chain.net/smartcontract/storagesc/blobber2_test.go
  code/go/0chain.net/smartcontract/storagesc/blobber_alloc_partition.go
  code/go/0chain.net/smartcontract/storagesc/blobber_alloc_partition_gen.go
  code/go/0chain.net/smartcontract/storagesc/blobber_challenge_alloc_partition.go
  code/go/0chain.net/smartcontract/storagesc/blobber_challenge_partition.go
  code/go/0chain.net/smartcontract/storagesc/blobber_challenges.go
  code/go/0chain.net/smartcontract/storagesc/blobber_challenges_gen.go
  code/go/0chain.net/smartcontract/storagesc/blobber_challenges_test.go
  code/go/0chain.net/smartcontract/storagesc/blobber_test.go
  code/go/0chain.net/smartcontract/storagesc/block_reward_test.go
  code/go/0chain.net/smartcontract/storagesc/challenge.go
  code/go/0chain.net/smartcontract/storagesc/challenge_ready_partition.go
  code/go/0chain.net/smartcontract/storagesc/challenge_ready_partition_gen.go
  code/go/0chain.net/smartcontract/storagesc/challenge_test.go
  code/go/0chain.net/smartcontract/storagesc/free_allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/handler.go
  code/go/0chain.net/smartcontract/storagesc/helper2_test.go
  code/go/0chain.net/smartcontract/storagesc/helper_test.go
  code/go/0chain.net/smartcontract/storagesc/models.go
  code/go/0chain.net/smartcontract/storagesc/models_gen.go
  code/go/0chain.net/smartcontract/storagesc/readpool.go
  code/go/0chain.net/smartcontract/storagesc/sc.go
  code/go/0chain.net/smartcontract/storagesc/stakepool_test.go
  code/go/0chain.net/smartcontract/storagesc/transactions_bench_test.go
  code/go/0chain.net/smartcontract/storagesc/writepool.go
  code/go/0chain.net/smartcontract/storagesc/writepool_test.go
  code/go/0chain.net/smartcontract/vestingsc/balances_test.go
  docker.local/config/sc.yaml
Labels: mainnet

#1247 Fix #1246 duplicate transactions being created
  PULL_REQUEST_TEMPLATE.md
  code/go/0chain.net/miner/protocol_block.go
Labels: bug, mainnet

#1248 Fix go-routine leak
  code/go/0chain.net/smartcontract/storagesc/allocation.go
Labels: bug

#884 Transaction: nonce
  code/go/0chain.net/chaincore/chain/state.go
  code/go/0chain.net/chaincore/chain/state/state_context.go
  code/go/0chain.net/chaincore/httpclientutil/http_client_util.go
  code/go/0chain.net/chaincore/httpclientutil/http_client_util_test.go
  code/go/0chain.net/chaincore/httpclientutil/transaction.go
  code/go/0chain.net/chaincore/node/self_node.go
  code/go/0chain.net/chaincore/state/state.go
  code/go/0chain.net/chaincore/state/state_test.go
  code/go/0chain.net/chaincore/transaction/entity.go
  code/go/0chain.net/chaincore/transaction/worker.go
  code/go/0chain.net/chaincore/wallet/wallet.go
  code/go/0chain.net/core/common/handler_test.go
  code/go/0chain.net/core/datastore/key_test.go
  code/go/0chain.net/core/logging/handler_test.go
  code/go/0chain.net/miner/protocol_block.go
  code/go/0chain.net/miner/protocol_block_main_test.go
  code/go/0chain.net/miner/round.go
  code/go/0chain.net/miner/worker.go
  code/go/0chain.net/smartcontract/minersc/miner.go
  code/go/0chain.net/smartcontract/multisigsc/test/blockchainclient.go
  docker.local/build.miner/Dockerfile
  docker.local/config/sc.yaml
Labels: enhancement, mainnet

#1025 Miner rewards
  .github/workflows/build-&-publish-docker-image.yml
  .github/workflows/system_tests.yml
  code/go/0chain.net/chaincore/chain/protocol_view_change.go
  code/go/0chain.net/chaincore/chain/state_handler.go
  code/go/0chain.net/chaincore/chain/state_handler_test.go
  code/go/0chain.net/chaincore/smartcontract/handler_test.go
  code/go/0chain.net/chaincore/smartcontractinterface/pool.go
  code/go/0chain.net/chaincore/smartcontractinterface/pool_gen.go
  code/go/0chain.net/chaincore/smartcontractinterface/pool_test.go
  code/go/0chain.net/smartcontract/benchmark/main/cmd/mpt.go
  code/go/0chain.net/smartcontract/dbs/event/miner.go
  code/go/0chain.net/smartcontract/dbs/event/sharder.go
  code/go/0chain.net/smartcontract/dbs/event/stakepool.go
  code/go/0chain.net/smartcontract/dbs/event/validator.go
  code/go/0chain.net/smartcontract/minersc/benchmark_rest_tests.go
  code/go/0chain.net/smartcontract/minersc/benchmark_setup.go
  code/go/0chain.net/smartcontract/minersc/benchmark_tests.go
  code/go/0chain.net/smartcontract/minersc/collect_reward.go
  code/go/0chain.net/smartcontract/minersc/delegate_pools.go
  code/go/0chain.net/smartcontract/minersc/fees.go
  code/go/0chain.net/smartcontract/minersc/fees2_test.go
  code/go/0chain.net/smartcontract/minersc/fees_test.go
  code/go/0chain.net/smartcontract/minersc/handler.go
  code/go/0chain.net/smartcontract/minersc/helper2_test.go
  code/go/0chain.net/smartcontract/minersc/helper_test.go
  code/go/0chain.net/smartcontract/minersc/miner.go
  code/go/0chain.net/smartcontract/minersc/miner_eventdb.go
  code/go/0chain.net/smartcontract/minersc/miner_node.go
  code/go/0chain.net/smartcontract/minersc/miner_node_gen.go
  code/go/0chain.net/smartcontract/minersc/miner_nodes.go
  code/go/0chain.net/smartcontract/minersc/miner_nodes_gen.go
  code/go/0chain.net/smartcontract/minersc/miner_test.go
  code/go/0chain.net/smartcontract/minersc/minersc.go
  code/go/0chain.net/smartcontract/minersc/models.go
  code/go/0chain.net/smartcontract/minersc/models_gen.go
  code/go/0chain.net/smartcontract/minersc/models_test.go
  code/go/0chain.net/smartcontract/minersc/sc.go
  code/go/0chain.net/smartcontract/minersc/sharder.go
  code/go/0chain.net/smartcontract/minersc/sharder_eventdb.go
  code/go/0chain.net/smartcontract/minersc/sharder_test.go
  code/go/0chain.net/smartcontract/stakepool/collect_reward.go
  code/go/0chain.net/smartcontract/stakepool/stakepool.go
  code/go/0chain.net/smartcontract/stakepool/unlock.go
  code/go/0chain.net/smartcontract/stakepool/userstakepoolgo.go
  code/go/0chain.net/smartcontract/storagesc/blobber_test.go
  code/go/0chain.net/smartcontract/storagesc/challenge_test.go
  code/go/0chain.net/smartcontract/storagesc/collect_reward.go
  code/go/0chain.net/smartcontract/storagesc/stakepool.go
  code/go/0chain.net/smartcontract/storagesc/stakepool_test.go
  code/go/0chain.net/smartcontract/zcnsc/authorizer.go
  code/go/0chain.net/smartcontract/zcnsc/stakepool.go
  docker.local/config/sc.yaml
Labels: high-priority, smart-contracts

#1229 New allocation request
  code/go/0chain.net/chaincore/config/config.go
  code/go/0chain.net/chaincore/smartcontract/handler_test.go
  code/go/0chain.net/sharder/handler_main.go
  code/go/0chain.net/smartcontract/benchmark/benchmark.go
  code/go/0chain.net/smartcontract/benchmark/main/config/benchmark.yaml
  code/go/0chain.net/smartcontract/benchmark/main/readme.md
  code/go/0chain.net/smartcontract/dbs/event/blobber.go
  code/go/0chain.net/smartcontract/dbs/event/blobber_test.go
  code/go/0chain.net/smartcontract/storagesc/alloation2_test.go
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/balances_test.go
  code/go/0chain.net/smartcontract/storagesc/benchmark_rest_tests.go
  code/go/0chain.net/smartcontract/storagesc/benchmark_setup.go
  code/go/0chain.net/smartcontract/storagesc/benchmark_tests.go
  code/go/0chain.net/smartcontract/storagesc/blobber.go
  code/go/0chain.net/smartcontract/storagesc/blobber_eventdb.go
  code/go/0chain.net/smartcontract/storagesc/blobber_test.go
  code/go/0chain.net/smartcontract/storagesc/challengepool.go
  code/go/0chain.net/smartcontract/storagesc/config.go
  code/go/0chain.net/smartcontract/storagesc/config_gen.go
  code/go/0chain.net/smartcontract/storagesc/config_settigns.go
  code/go/0chain.net/smartcontract/storagesc/config_settings_test.go
  code/go/0chain.net/smartcontract/storagesc/free_allocation.go
  code/go/0chain.net/smartcontract/storagesc/free_allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/handler.go
  code/go/0chain.net/smartcontract/storagesc/helper_test.go
  code/go/0chain.net/smartcontract/storagesc/models.go
  code/go/0chain.net/smartcontract/storagesc/models_test.go
  code/go/0chain.net/smartcontract/storagesc/sc.go
  code/go/0chain.net/smartcontract/storagesc/stakepool.go
  code/go/0chain.net/smartcontract/storagesc/writepool.go
  docker.local/config/sc.yaml
Labels: enhancement, mainnet

#1250 Feature/remove all blobbers
  code/go/0chain.net/chaincore/chain/state_handler_test.go
  code/go/0chain.net/smartcontract/benchmark/benchmark.go
  code/go/0chain.net/smartcontract/benchmark/main/cmd/command.go
  code/go/0chain.net/smartcontract/benchmark/main/cmd/suites.go
  code/go/0chain.net/smartcontract/benchmark/main/config/benchmark.yaml
  code/go/0chain.net/smartcontract/storagesc/alloation2_test.go
  code/go/0chain.net/smartcontract/storagesc/allocation.go
  code/go/0chain.net/smartcontract/storagesc/allocation_test.go
  code/go/0chain.net/smartcontract/storagesc/benchmark_setup.go
  code/go/0chain.net/smartcontract/storagesc/benchmark_tests.go
  code/go/0chain.net/smartcontract/storagesc/blobber.go
  code/go/0chain.net/smartcontract/storagesc/blobber_test.go
  code/go/0chain.net/smartcontract/storagesc/free_allocation.go
  code/go/0chain.net/smartcontract/storagesc/handler.go
  code/go/0chain.net/smartcontract/storagesc/helper_test.go
  code/go/0chain.net/smartcontract/storagesc/models.go
  code/go/0chain.net/smartcontract/storagesc/sc.go
  code/go/0chain.net/smartcontract/storagesc/sorted_list.go
  code/go/0chain.net/smartcontract/storagesc/transactions_bench_test.go
  docs/unit-tests.md
Labels: mainnet
