Repository 0chain/0chain, pull requests merged in 2023-03, with the labels that each got.

#2183 Empty allocation root
  code/go/0chain.net/smartcontract/storagesc/challenge.go
Labels: bug

#2143 Fix: reconciliation problem
  code/go/0chain.net/chaincore/chain/state_handler_test.go
  code/go/0chain.net/chaincore/client/entity.go
  code/go/0chain.net/chaincore/smartcontract/handler_test.go
  code/go/0chain.net/chaincore/state/state.go
  code/go/0chain.net/smartcontract/dbs/event/allocation_blobber_term_test.go
  code/go/0chain.net/smartcontract/dbs/event/burn_ticket.go
  code/go/0chain.net/smartcontract/dbs/event/burn_ticket_test.go
  code/go/0chain.net/smartcontract/dbs/event/enums.go
  code/go/0chain.net/smartcontract/dbs/event/eventdb.go
  code/go/0chain.net/smartcontract/dbs/event/process.go
  code/go/0chain.net/smartcontract/dbs/event/user.go
  code/go/0chain.net/smartcontract/dbs/goose/migrations/001_events_db.sql
  code/go/0chain.net/smartcontract/zcnsc/benchmark_rest_tests.go
  code/go/0chain.net/smartcontract/zcnsc/burn.go
  code/go/0chain.net/smartcontract/zcnsc/burn_test.go
  code/go/0chain.net/smartcontract/zcnsc/burn_ticket.go
  code/go/0chain.net/smartcontract/zcnsc/context_helpers_test.go
  code/go/0chain.net/smartcontract/zcnsc/factory_helpers_test.go
  code/go/0chain.net/smartcontract/zcnsc/handler.go
  code/go/0chain.net/smartcontract/zcnsc/handler_test.go
  code/go/0chain.net/smartcontract/zcnsc/mint.go
  code/go/0chain.net/smartcontract/zcnsc/mint_test.go
  code/go/0chain.net/smartcontract/zcnsc/sc.go
  docker.local/bin/build.base.sh
  docker.local/build.base/Dockerfile.build_base
Labels: enhancement, mainnet, api

#2220 Fix: authorizer fee rewards
  code/go/0chain.net/smartcontract/stakepool/spenum/enums.go
  code/go/0chain.net/smartcontract/zcnsc/context_helpers_test.go
  code/go/0chain.net/smartcontract/zcnsc/mint.go
  code/go/0chain.net/smartcontract/zcnsc/mint_test.go
Labels: bug, smart-contracts

#2230 Fix/event processing panic
  code/go/0chain.net/chaincore/chain/state.go
  code/go/0chain.net/smartcontract/dbs/event/enums.go
  code/go/0chain.net/smartcontract/dbs/event/event.go
  code/go/0chain.net/smartcontract/dbs/event/partition.go
  code/go/0chain.net/smartcontract/dbs/event/process.go
  code/go/0chain.net/smartcontract/dbs/event/stakepool.go
  code/go/0chain.net/smartcontract/dbs/event/user.go
  code/go/0chain.net/smartcontract/dbs/event/user_aggregate.go
  code/go/0chain.net/smartcontract/zcnsc/context_helpers_test.go
  code/go/0chain.net/smartcontract/zcnsc/mint.go
Labels: bug
