Repository 0chain/0chain, pull requests merged in 2023-11, with the labels that each got.

#2926 Hotfix: add Authorizer network change in conductor test workflow
  .github/workflows/conductor-authorizer-tests.yml
Labels: enhancement, critical

#2936 Feat/download verify ct
  code/go/0chain.net/conductor/conductor/executor.go
  code/go/0chain.net/conductor/conductrpc/state.go
  code/go/0chain.net/conductor/config/config.go
  code/go/0chain.net/conductor/config/execute.go
  code/go/0chain.net/conductor/config/registry.go
  code/go/0chain.net/conductor/config/types.go
  docker.local/bin/conductor/download.sh
  docker.local/bin/conductor/download_with_verification.sh
  docker.local/bin/conductor/init_allocation_free_read.sh
  docker.local/bin/conductor/update_blobber_config.sh
  docker.local/config/conductor.blobber-6.yaml
  docker.local/config/conductor.config.yaml
Labels: wip

#2945 Hotfix: update ZCN config for node recovery tests
  .github/workflows/conductor-node-recovery-03-tests.yml
Labels: bug, conductor test

#2982 Feature: implement fork per run strategy
  .github/workflows/build-&-publish-docker-image.yml
  .github/workflows/system_tests.yml
Labels: enhancement
