Repository 0chain/0chain, pull requests merged in 2023-06, with the labels that each got.

#2473 Feature: add CI workflow params for graph-node
  .github/workflows/build-&-publish-docker-image.yml
  .github/workflows/system_tests.yml
Labels: CI Pipeline

#2517 changed runner for conductor test
  .github/workflows/conductor-blobber-tests-02.yml
Labels: wip

#2551 Check the error after Merge() and return if not nil
  code/go/0chain.net/sharder/transaction.go
Labels: bug
